<div class="store-info__container">
    <div class="working-hours">Mon-Thu: 9:00 AM - 5:30 PM</div>
    <div class="address">Visit our showroom in 1234 Street Adress City Address, 1234  Contact Us</div>
    <div class="contacts">
        <div class="phone-number">Call Us: (00) 1234 5678</div>
        <div class="social-links">
            <a href="#">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/social-icons/facebook.svg')) ?>"
                     alt="<?= $block->escapeHtml(__('Facebook icon')); ?>">
            </a>
            <a href="#">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/social-icons/insta-icon.svg')) ?>"
                     alt="<?= $block->escapeHtml(__('Instagram icon')); ?>">
            </a>
        </div>
    </div>
</div>
