<div class="footer-menu">
    <div class="footer-menu__block block-general">
        <h4 class="footer__block-heading">Information</h4>
        <ul class="footer-block__items">
            <li class="footer-block__item">
                <a href="#" title="About us" class="footer-block__link">About us</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="About zip" class="footer-block__link">About zip</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Privacy Policy" class="footer-block__link">Privacy Policy</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Search" class="footer-block__link">Search</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Terms" class="footer-block__link">Terms</a>
            </li>
            <li class="footer-block__item">
                <span href="#" title="Orders and returns" class="footer-block__link">Orders <span class="text-lowercase">and</span> returns</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Contact us" class="footer-block__link">Contact us</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Advanced search" class="footer-block__link">Advanced search</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Newsletter subscription" class="footer-block__link">Newsletter subscription</a>
            </li>
        </ul>
    </div>
    <div class="footer-menu__block block-pc-parts">
        <h4 class="footer__block-heading">PC parts</h4>
        <ul class="footer-block__items">
            <li class="footer-block__item">
                <a href="#" title="CPUS" class="footer-block__link">CPUS</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Add on cards" class="footer-block__link">Add on cards</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Hard drives (internal)" class="footer-block__link">Hard drives (internal)</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Graphic cards" class="footer-block__link">Graphic cards</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Keyboards / Mice" class="footer-block__link">Keyboards/Mice</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Cases / Power supplies / Cooling" class="footer-block__link">Cases / Power supplies / Cooling</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="RAM (Memory)" class="footer-block__link">RAM (Memory)</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Software" class="footer-block__link">Software</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Speakers / Headsets" class="footer-block__link">Speakers / Headsets</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Motherboards" class="footer-block__link">Motherboards</a>
            </li>
        </ul>
    </div>
    <div class="footer-menu__block block-pcs">
        <h4 class="footer__block-heading">Desktop PCs</h4>
        <ul class="footer-block__items">
            <li class="footer-block__item">
                <a href="#" title="Custom PCs" class="footer-block__link">Custom PCs</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Servers" class="footer-block__link">Servers</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="MCI All-in-one PCs" class="footer-block__link">MCI All-<span class="text-lowercase">in</span>-one PCs</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="HP/Compaq PCs" class="footer-block__link">HP/Compaq PCs</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="ASUS PCs" class="footer-block__link">ASUS PCs</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Tecs PCs" class="footer-block__link">Tecs PCs</a>
            </li>
        </ul>
    </div>
    <div class="footer-menu__block block-laptops">
        <h4 class="footer__block-heading">Laptops</h4>
        <ul class="footer-block__items">
            <li class="footer-block__item">
                <a href="#" title="Everyday use notebooks" class="footer-block__link">Everyday use notebooks</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="MSI workstation series" class="footer-block__link">MSI workstation series</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="MSI prestige series" class="footer-block__link">MSI prestige series</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Tablets and pads" class="footer-block__link">Tablets <span class="text-lowercase">and</span> pads</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Netbooks" class="footer-block__link">Netbooks</a>
            </li>
            <li class="footer-block__item">
                <a href="#" title="Infinity gaming notebooks" class="footer-block__link">Infinity gaming notebooks</a>
            </li>
        </ul>
    </div>
    <div class="footer-menu__block contacts-block">
        <h4 class="footer__block-heading">Address</h4>
        <div class="footer-block__items contacts-block__items">
            <span class="contacts-block__item contacts-block__address">Address: 1234 Street Adress City Address, 1234</span>
            <span class="contacts-block__item contacts-block__phone-number"> Phones:
                <a href="(00) 1234 5678">(00) 1234 5678</a>
            </span>
            <span class="contacts-block__item contacts-block__open-hours">We are open: Monday-Thursday: 9:00 AM - 5:30 PM</span>
            <span class="contacts-block__item contacts-block__open-hours">Friday: 9:00 AM - 6:00 PM</span>
            <span class="contacts-block__item contacts-block__open-hours">Saturday: 11:00 AM - 5:00 PM</span>
            <span class="contacts-block__item contacts-block__email"> E-mail:
                 <a href="mailto:shop@email.com">shop@email.com</a>
            </span>
        </div>
    </div>
</div>
