<div class="payment-methods">
    <div class="payment-card">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/payments/paypal.svg')) ?>"
             alt="<?= $block->escapeHtml(__('Paypal card icon')); ?>">
    </div>
    <div class="payment-card">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/payments/visa.svg')) ?>"
             alt="<?= $block->escapeHtml(__('Visa card icon')); ?>">
    </div>
    <div class="payment-card">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/payments/maestro.svg')) ?>"
             alt="<?= $block->escapeHtml(__('Maestro card icon')); ?>">
    </div>
    <div class="payment-card">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/payments/discover.svg')) ?>"
             alt="<?= $block->escapeHtml(__('Discover card icon')); ?>">
    </div>
    <div class="payment-card">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/payments/american-express.svg')) ?>"
             alt="<?= $block->escapeHtml(__('American-express card icon')); ?>">
    </div>
</div>
