<section class="slider-slick" data-mage-init='{"slick": {}}'>
    <div>
        <p class="testimonial">
            My first order arrived today in perfect condition.  From the time I sent a question about the item to making
            the purchase, to the shipping and now the delivery, your company, Tecs, has stayed in touch.  Such great service.
            I look forward to shopping on your site in the future and would highly recommend it.
        </p>
      </div>
    <div>
        <p class="testimonial">
            Great communication, great service. Highly recommended.
        </p>
    </div>
    <div>
        <p class="testimonial">
            I’ve purchased 8 desktops both professionally and personally over the last 9 years. Great service, fantastic
            support & repair technicians. I go nowhere else for my computers.
        </p>
    </div>
    <div>
        <p class="testimonial">
            Andre is the best!!! He gave me so much product and operation info. He really cares and loves what he does!
            He even stayed late and off the clock to make sure i wad good. Maybe the best customer service experience I’ve ever had!
            Tech Store is the real deal!
        </p>
    </div>
</section>
