<div class="social-links">
    <a href="#">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/social-icons/facebook.svg')) ?>"
             alt="<?= $block->escapeHtml(__('Facebook icon')); ?>">
    </a>
    <a href="#">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/social-icons/insta-icon.svg')) ?>"
             alt="<?= $block->escapeHtml(__('Instagram icon')); ?>">
    </a>
</div>
