<div class="menu" id="footer-menu" data-mage-init='{"accordion": {}}'>
    <div class="menu__column">
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4><?php echo __('About Nintendove')?></h4>
            </div>
        </div>
        <ul data-role="content">
            <li><a href="#" title="<?php echo __('Company Info')?>"><?php echo __('Company Info')?></a></li>
            <li><a href="#" title="<?php echo __('Careers')?>"><?php echo __('Careers')?></a></li>
            <li><a href="#" title="<?php echo __('CSR Report')?>"><?php echo __('CSR Report')?></a></li>
            <li><a href="#" title="<?php echo __('Sitemap')?>"><?php echo __('Sitemap')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4><?php echo __('Store Support')?></h4>
            </div>
        </div>
        <ul data-role="content">
            <li><a href="#" title="<?php echo __('Order Status')?>"><?php echo __('Order Status')?></a></li>
            <li><a href="#" title="<?php echo __('Shipping & Processing')?>"><?php echo __('Shipping & Processing')?></a></li>
            <li><a href="#" title="<?php echo __('Returns & Exchanges')?>"><?php echo __('Returns & Exchanges')?></a></li>
            <li><a href="#" title="<?php echo __('Orders & Lists')?>"><?php echo __('Orders & Lists')?></a></li>
            <li><a href="#" title="<?php echo __('FAQ')?>"><?php echo __('FAQ')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('Contact Us')?></a></li>
            <li><a href="#" title="<?php echo __('Help Topics')?>"><?php echo __('Help Topics')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <div data-role="collapsible">
            <div data-role="trigger">
                <h4><?php echo __('Product Information')?></h4>
            </div>
        </div>
        <ul data-role="content">
            <li><a href="#" title="<?php echo __('Product Support')?>"><?php echo __('Product Support')?></a></li>
            <li><a href="#" title="<?php echo __('Repair Help')?>"><?php echo __('Repair Help')?></a></li>
            <li><a href="#" title="<?php echo __('Product Warranty')?>"><?php echo __('Product Warranty')?></a></li>
            <li><a href="#" title="<?php echo __('Health & Safety Precautions')?>"><?php echo __('Health & Safety Precautions')?></a></li>
            <li><a href="#" title="<?php echo __('Nintendo Product Recycling')?>"><?php echo __('Nintendo Product Recycling')?></a></li>
            <li><a href="#" title="<?php echo __('Refurbished Products')?>"><?php echo __('Refurbished Products')?></a></li>
        </ul>
    </div>
</div>
