<div class="testimonials-section__container">
    <section class="testimonials-section">
        <div class="slider-slick">
            <div class="slider-content">
                <span class="quotes">‘’</span>
                <div class="testimonial">
                    <p class="testimonial__text">
                        My first order arrived today in perfect condition.  From the time I sent a question about the item to making
                        the purchase, to the shipping and now the delivery, your company, Tecs, has stayed in touch.  Such great service.
                        I look forward to shopping on your site in the future and would highly recommend it.
                    </p>
                    <span class="testimonial__author">- Tama Brown</span>
                </div>
            </div>
            <div class="slider-content">
                <span class="quotes">‘’</span>
                <div class="testimonial">
                    <p class="testimonial__text"">
                    Great communication, great service. Highly recommended. Maybe the best customer service experience I’ve ever had!
                    </p>
                    <span class="testimonial__author">- Peter McMillan</span>
                </div>
            </div>
            <div class="slider-content">
                <span class="quotes">‘’</span>
                <div class="testimonial">
                    <p class="testimonial__text">
                        I’ve purchased 8 desktops both professionally and personally over the last 9 years. Great service, fantastic
                        support & repair technicians. I go nowhere else for my computers.
                    </p>
                    <span class="testimonial__author">- Eva Ferguson</span>
                </div>
            </div>
            <div class="slider-content">
                <span class="quotes">‘’</span>
                <div class="testimonial">
                    <p class="testimonial__text">
                        Andre is the best!!! He gave me so much product and operation info. He really cares and loves what he does!
                        He even stayed late and off the clock to make sure i wad good. Maybe the best customer service experience I’ve ever had!
                        Tech Store is the real deal!
                    </p>
                    <span class="testimonial__author">- Eveline Cat</span>
                </div>
            </div>
        </div>
        <button class="button-transparent">Leave us a review</button>
    </section>
</div>
