<section class="custom-slider__container">
    <div class="custom-slider" data-mage-init='{"slider2": {}}'>
        <div class="custom-slider__slide">
            <div class="custom-slider__slide-info">
                <p class="heading">Outplay the Competittion</p>
                <p class="text">
                    Experience a 40% boost in computing from last generation. MSI Desktop equips the
                    10th Gen. Intel® Core™ i7 processor with the upmost computing power to bring you an unparalleled gaming
                    experience.
                </p>
                <p class="text">
                    *Performance compared to i7-9700. Specs varies by model.
                </p>
            </div>
            <div class="custom-slider__slide-image">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/banner-slider/intel-core.png')) ?>"
                     alt="<?= $block->escapeHtml(__('Intel core i7')); ?>">
            </div>
        </div>
        <div class="custom-slider__slide">
            <div class="custom-slider__slide-info">
                <p class="heading">Outplay the Competittion</p>
                <p class="text">
                    Experience a 40% boost in computing from last generation. MSI Desktop equips the
                    10th Gen. Intel® Core™ i7 processor with the upmost computing power to bring you an unparalleled gaming
                    experience.
                </p>
                <p class="text">
                    *Performance compared to i7-9700. Specs varies by model.
                </p>
            </div>
            <div class="custom-slider__slide-image">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/banner-slider/intel-core.png')) ?>"
                     alt="<?= $block->escapeHtml(__('Intel core i7')); ?>">
            </div>
        </div>
        <div class="custom-slider__slide">
            <div class="custom-slider__slide-info">
                <p class="heading">Outplay the Competittion</p>
                <p class="text">
                    Experience a 40% boost in computing from last generation. MSI Desktop equips the
                    10th Gen. Intel® Core™ i7 processor with the upmost computing power to bring you an unparalleled gaming
                    experience.
                </p>
                <p class="text">
                    *Performance compared to i7-9700. Specs varies by model.
                </p>
            </div>
            <div class="custom-slider__slide-image">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Magento_Theme::images/banner-slider/intel-core.png')) ?>"
                     alt="<?= $block->escapeHtml(__('Intel core i7')); ?>">
            </div>
        </div>
    </div>
</section>

